name: build-docker-artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t metho .

      - name: Save image to tar
        run: docker save metho -o metho.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metho
          path: metho.tar
